import operator as op
from functools import reduce
from math import factorial

def ncr(n, r):
    r = min(r, n-r)
    numer = reduce(op.mul, range(n, n-r, -1), 1)
    denom = reduce(op.mul, range(1, r+1), 1)
    return numer / denom

NUM = 11

print("const static double COEFF[%d][%d][%d][%d]={" % (NUM,NUM,2*NUM+2,NUM))
for n in range(NUM):
    if n != 0:
        print(',',end='')
    print("  {")
    for l in range(NUM):
        if l != 0:
            print(',',end='')
        print("    {")
        for a in range(2*NUM+2):
            if a != 0:
                print(',',end='')
            print("      {")
            print(*[ncr(n+a,n-k)*(-1)**k/factorial(k) for k in range(NUM)], sep=', ')
            print("      }")
        print("    }")
    print("  }")
print("};")
print("// This code was automatically generated by laguerregen.py.")
